spring:
  application:
    name: consumer
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
fdfs:
  tracker-list: 10.92.3.99:22122
  web-server-url: http://10.92.3.99
  so-timeout: 1500
  connect-timeout: 600