spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/stu_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password:


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #    host: 127.0.0.1
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0s

    jedis:
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1s
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0

#    host: localhost
#    port: 6379
#    password:password

logging:
  level:
    root: info
    com.yyg.sbt.store.mapper: debug

#外部系统路径配置
#ams:
#  appId:
#  appSecret:
#  sysUrl: http://localhost:8080
#  getByEid: /api/department/get_by_eid
#
#email:
#  host: smtp.ym.163.com
#  port: 25
#  form: yyg0429@163.com #chao521it@163.com
#  username: yyg0429@163.com
#  password:
email:
  host: smtp.exmail.qq.com #smtp.163.com
  port: 465
  form: yyg0429@163.com #chao521it@163.com
  username: yyg0429@163.com
  password:

ams:
  appId:
  appSecret:
  sysUrl: http://localhost:8080
  getByEid: /api/department/get_by_eid